Feat/popup
NBCAMP-EZPZ/EZPZ-User pull request #10
Opened 2024-07-24 07:55 UTC by ydh5017

## #️⃣연관된 이슈

> ex) #9

## 📝작업 내용
1. 팝업 상태별 목록 조회
 - 진행 예정, 진행 중,종료
2. 팝업 상세 조회
 - 심사 중 또는 취소된 팝업 예외

### 스크린샷 (선택)
 - 팝업 상태별 목록 조회
<img width="459" alt="image" src="https://github.com/user-attachments/assets/d7fde99b-16ef-4150-83ff-5ceacceb9519">

 - 팝업 상세 조회
<img width="783" alt="image" src="https://github.com/user-attachments/assets/1ff585ea-bfa9-48b4-9482-f5b2944ad618">

## 💬리뷰 요구사항(선택)

2024-07-24 08:12 UTC, llocr reviewed
수고하셨습니다! 👍

2024-07-25 01:39 UTC, llocr approved these changes
`@ManyToOne`으로 설정된 부분들에 `FetchType.LAZY`가 설정되지 않은 부분들이 있더라구요!
저것들만 수정해주시면 좋을 것 같습니다 👍

2024-07-25 01:39 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Likes.java
> +    private User user;
`FetchType.LAZY`로 설정되면 좋을 것 같습니다!

2024-07-25 01:39 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
> +    private Host host;
이 부분도 `FetchType.LAZY`로 설정되면 좋을 것 같습니다!

2024-07-25 02:29 UTC, uh1205 requested changes

2024-07-25 02:29 UTC, uh1205 commented on src/main/java/com/sparta/ezpzuser/domain/popup/controller/PopupController.java
> +        Page<?> popupList = popupService.findAllPopupsByStatus(pageable, cond);
popupStatus 하나만 서비스에 넘겨야 한다면 굳이 condition 클래스를 안 만들어도 될 듯 하네요!

2024-07-25 02:29 UTC, uh1205 commented on src/main/java/com/sparta/ezpzuser/domain/popup/controller/PopupController.java
> +        PageUtil.validatePageableWithPage(pageable, popupList);
페이지 validation은 서비스에서 하는게 더 좋아보입니다!

2024-07-25 02:29 UTC, uh1205 commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Likes.java
> +public class Likes {
클래스명은 Like로 두고, 테이블명을 Likes로 변경해야 나중에 헷갈리지 않을 듯 하네요!

2024-07-25 02:29 UTC, uh1205 commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Likes.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-07-25 02:29 UTC, uh1205 commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-07-25 02:29 UTC, uh1205 commented on src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
> +    }
메서드가 너무 분리되어 있어서 가독성이 떨어지는 것 같아요. 다음과 같이 변경해보는건 어때요??
```suggestion
    private final JPAQueryFactory queryFactory;

    @Override
    public Page<Popup> findAllPopupsByStatus(Pageable pageable, String popupStatus) {
        // 데이터 조회 쿼리
        List<Popup> popups = queryFactory
                .selectFrom(popup)
                .where(
                        popup.approvalStatus.eq(ApprovalStatus.APPROVED),
                        popupStatusEq(popupStatus)
                )
                .offset(pageable.getOffset())
                .limit(pageable.getPageSize())
                .orderBy(popup.createdAt.desc())
                .fetch();

        // 전체 카운트 쿼리
        Long totalSize = queryFactory
                .select(Wildcard.count)
                .from(popup)
                .where(
                        popup.approvalStatus.eq(ApprovalStatus.APPROVED),
                        popupStatusEq(popupStatus)
                )
                .fetchOne();

        return PageableExecutionUtils.getPage(popups, pageable, () -> RepositoryUtil.getTotal(totalCount));
    }
```

2024-07-25 04:12 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/popup/controller/PopupController.java
> +        Page<?> popupList = popupService.findAllPopupsByStatus(pageable, cond);
나중에 호스트별과 같은 조건이 생길 가능성과 유저, 호스트, 어드민 통일성을 위해서 일단 생성해뒀습니다.

2024-07-25 04:12 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/popup/controller/PopupController.java
> +        PageUtil.validatePageableWithPage(pageable, popupList);
수정하겠습니다.

2024-07-25 04:14 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Likes.java
> +public class Likes {
지금 현재 테이블명 likes 입니다. like로 하면 예약어로 인한 오류가 발생합니다. 엔티티명은 통일성을 위해서 입니다.

2024-07-25 04:14 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Likes.java
> +    @ManyToOne
수정하겠습니다.

2024-07-25 04:14 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
> +    @ManyToOne
수정하겠습니다.

2024-07-25 04:16 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
> +    }
수정하겠습니다.

2024-07-25 05:43 UTC, M1ngD0ng approved these changes

2024-07-25 05:47 UTC, merged