Feat/좋아요
NBCAMP-EZPZ/EZPZ-User pull request #24
Opened 2024-07-25 14:20 UTC by ydh5017

## #️⃣연관된 이슈

> ex) #23

## 📝작업 내용

> 팝업, 굿즈 좋아요 토글, 좋아요한 컨텐츠(팝업, 굿즈) 목록 조회

### 스크린샷 (선택)
 - 팝업, 굿즈 좋아요 토글
<img width="370" alt="image" src="https://github.com/user-attachments/assets/098df863-95cf-4a01-8ab5-be50352f4515">

 - 좋아요한 컨텐츠(팝업) 목록 조회
<img width="717" alt="image" src="https://github.com/user-attachments/assets/52401b89-e38d-49c3-b2cd-63b8b9718b63">

 - 좋아요한 컨텐츠(굿즈) 목록 조회
<img width="697" alt="image" src="https://github.com/user-attachments/assets/789a4865-0a74-4d56-ab3d-98e087b758fc">

## 💬리뷰 요구사항(선택)
팝업 레포지토리들이 겹쳐서 하나로 합쳤습니다

2024-07-25 15:43 UTC, llocr requested changes
코드 작성하시느라 수고하셨습니다!
리뷰 확인해 주세요 :) 👍

2024-07-25 15:43 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/item/entity/Item.java
> +        }
아래와 같이 변경하면 더 좋을 것 같습니다! 👍

```java
if (b) {
    this.likeCount++;
} else if (this.likeCount > 0) {
    this.likeCount--;
}
```

2024-07-25 15:43 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
> +        }
저는 switch-case 문을 사용하는 게 더 좋아 보이는데 어떠신가요!

```java
switch (content.getContentType()) {
    case "popup" -> popupLike(content, user);
    case "item" -> itemLike(content, user);
    default -> throw new CustomException(ErrorType.INVALID_CONTENT_TYPE);
}
```

2024-07-25 15:43 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
> +                    .toList();
이 부분은 popup과 item 두 곳에서 모두 겹치는데, 공통 메소드로 분리해서 사용하는 건 어떨까요?

2024-07-25 15:43 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
> +                .orElse(null);
null로 받아오기 보다는, `Optional` 사용하는 게 좋을 것 같습니다!

2024-07-25 15:43 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
> +            }
여기도 위와 같이 변경하면 좋을 것 같네요! 😀

2024-07-25 15:43 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
> +    }
이 부분들도 `switch-case`문을 사용한다면 더 간결해 질 것 같습니다!

2024-07-25 15:43 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
> +                .where(
만약 유저가 좋아요 한 팝업이 많다면, host에 접근해서 이름을 가져올 때,
`n+1` 문제가 발생할 것 같은데 `fetch join`을 해오는 것이 좋지 않을까요?

2024-07-25 15:45 UTC, llocr commented on src/main/java/com/sparta/ezpzuser/domain/like/controller/LikeController.java
> +        return getResponseEntity(contentList, "타입별 좋아요한 한 컨테츠 목록 조회 성공");
🚨 오타 있어용!!

2024-07-26 01:37 UTC, M1ngD0ng approved these changes

2024-07-26 02:04 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/item/entity/Item.java
> +        }
수정했습니다.

2024-07-26 02:05 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
> +        }
수정했습니다.

2024-07-26 02:05 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
> +                    .toList();
수정했습니다.

2024-07-26 02:05 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
> +                .orElse(null);
수정했습니다.

2024-07-26 02:05 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
> +            }
수정했습니다.

2024-07-26 02:05 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
> +    }
수정했습니다.

2024-07-26 02:05 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
> +                .where(
수정했습니다.

2024-07-26 02:06 UTC, ydh5017 commented on src/main/java/com/sparta/ezpzuser/domain/like/controller/LikeController.java
> +        return getResponseEntity(contentList, "타입별 좋아요한 한 컨테츠 목록 조회 성공");
수정했습니다.

2024-07-26 02:33 UTC, llocr approved these changes

2024-07-26 02:33 UTC, merged